var answers = [
    "ABACK",
    "ABASE",
    "ABATE",
    "ABBEY",
    "ABYSS",
    "ACUTE",
    "ADMIT",
    "ADOBE",
    "ADOPT",
    "ADORE",
    "AGAPE",
    "AGATE",
    "AGREE",
    "AHEAD",
    "ALBUM",
    "ALIEN",
    "ALIKE",
    "ALLOW",
    "ALOFT",
    "ALONE",
    "ALOUD",
    "ALPHA",
    "ALTAR",
    "ALTER",
    "AMBER",
    "AMPLE",
    "ANGRY",
    "ANTIC",
    "AORTA",
    "APHID",
    "APPLE",
    "APPLY",
    "APRON",
    "APTLY",
    "ARGUE",
    "AROMA",
    "ASIDE",
    "ASKEW",
    "ASSET",
    "ATOLL",
    "ATONE",
    "AUDIT",
    "AVERT",
    "AWAKE",
    "AWFUL",
    "AXIOM",
    "BADGE",
    "BADLY",
    "BAKER",
    "BANAL",
    "BASIC",
    "BATON",
    "BATTY",
    "BAYOU",
    "BEADY",
    "BEEFY",
    "BEGIN",
    "BEING",
    "BELCH",
    "BELIE",
    "BELLY",
    "BENCH",
    "BERTH",
    "BIOME",
    "BLACK",
    "BLAND",
    "BLEED",
    "BLOKE",
    "BLOWN",
    "BLUFF",
    "BLURB",
    "BLURT",
    "BLUSH",
    "BOOBY",
    "BOOST",
    "BOOZE",
    "BOOZY",
    "BOUGH",
    "BRAID",
    "BRAKE",
    "BRAVE",
    "BREAK",
    "BRIAR",
    "BRIBE",
    "BRINE",
    "BRING",
    "BRINK",
    "BRISK",
    "BUGGY",
    "CACAO",
    "CANNY",
    "CARGO",
    "CARRY",
    "CATER",
    "CATCH",
    "CAULK",
    "CHAFE",
    "CHAMP",
    "CHANT",
    "CHARD",
    "CHARM",
    "CHEAT",
    "CHEEK",
    "CHEST",
    "CHIEF",
    "CHILL",
    "CHOKE",
    "CHORD",
    "CHUNK",
    "CHUTE",
    "CIGAR",
    "CINCH",
    "CIVIC",
    "CLASS",
    "CLEAN",
    "CLICK",
    "CLING",
    "CLOCK",
    "CLOTH",
    "CLOWN",
    "CLUCK",
    "COAST",
    "COLON",
    "COMET",
    "COMMA",
    "CONDO",
    "CONIC",
    "CORNY",
    "COULD",
    "COUNT",
    "COYLY",
    "CRAMP",
    "CRANK",
    "CRASS",
    "CRATE",
    "CRAVE",
    "CRAZE",
    "CRAZY",
    "CREAK",
    "CREPT",
    "CRIMP",
    "CROAK",
    "CROSS",
    "CRUST",
    "CYNIC",
    "DANCE",
    "DANDY",
    "DEATH",
    "DEBUG",
    "DELTA",
    "DELVE",
    "DENIM",
    "DEPOT",
    "DEPTH",
    "DIGIT",
    "DODGE",
    "DONOR",
    "DOUBT",
    "DOWRY",
    "DOZEN",
    "DRAIN",
    "DREAM",
    "DRINK",
    "DRIVE",
    "DROLL",
    "DUCHY",
    "DUTCH",
    "DWARF",
    "EGRET",
    "EJECT",
    "ELDER",
    "ELOPE",
    "ELUDE",
    "ENEMA",
    "ENJOY",
    "EPOCH",
    "EPOXY",
    "EQUAL",
    "ERODE",
    "ERROR",
    "ESSAY",
    "EVADE",
    "EXCEL",
    "EXIST",
    "EXTRA",
    "EXULT",
    "FARCE",
    "FAULT",
    "FAVOR",
    "FEAST",
    "FEIGN",
    "FERRY",
    "FEWER",
    "FIELD",
    "FINER",
    "FIRST",
    "FISHY",
    "FIXER",
    "FJORD",
    "FLAIL",
    "FLAIR",
    "FLESH",
    "FLICK",
    "FLING",
    "FLIRT",
    "FLOAT",
    "FLOCK",
    "FLOOD",
    "FLOOR",
    "FLOSS",
    "FLOUT",
    "FLUFF",
    "FLUME",
    "FOCAL",
    "FOCUS",
    "FOGGY",
    "FORAY",
    "FORGE",
    "FORGO",
    "FORTH",
    "FOUND",
    "FOYER",
    "FRAME",
    "FRESH",
    "FROCK",
    "FRONT",
    "FROTH",
    "FUNGI",
    "GAMER",
    "GAMMA",
    "GAUDY",
    "GAUZE",
    "GAWKY",
    "GECKO",
    "GIANT",
    "GIRTH",
    "GLASS",
    "GLEAN",
    "GLOAT",
    "GLOOM",
    "GLORY",
    "GLYPH",
    "GOLEM",
    "GONER",
    "GOOSE",
    "GORGE",
    "GOUGE",
    "GRADE",
    "GRATE",
    "GREAT",
    "GREET",
    "GRIME",
    "GRIMY",
    "GRIPE",
    "GROIN",
    "GROUP",
    "GROVE",
    "GROWL",
    "GRUEL",
    "GUILD",
    "GULLY",
    "HAIRY",
    "HAPPY",
    "HATCH",
    "HAVOC",
    "HEADY",
    "HEATH",
    "HEIST",
    "HELIX",
    "HERON",
    "HINGE",
    "HOARD",
    "HOMER",
    "HOWDY",
    "HUMAN",
    "HUMOR",
    "HUMPH",
    "HUNKY",
    "HUTCH",
    "HYPER",
    "IMPEL",
    "INANE",
    "INEPT",
    "INERT",
    "INFER",
    "INPUT",
    "INTER",
    "IONIC",
    "IRONY",
    "ISLET",
    "ITCHY",
    "IVORY",
    "JAUNT",
    "JOUST",
    "JUDGE",
    "KARMA",
    "KEBAB",
    "KHAKI",
    "KNOCK",
    "KNOLL",
    "KOALA",
    "LABEL",
    "LABOR",
    "LAPEL",
    "LAPSE",
    "LARVA",
    "LAYER",
    "LEAPT",
    "LEAVE",
    "LEERY",
    "LEMON",
    "LIBEL",
    "LIGHT",
    "LILAC",
    "LINEN",
    "LIVER",
    "LOFTY",
    "LOOPY",
    "LOSER",
    "LOWLY",
    "LUNAR",
    "LUSTY",
    "LYING",
    "MADAM",
    "MAGIC",
    "MAIZE",
    "MAJOR",
    "MANLY",
    "MANOR",
    "MAPLE",
    "MARRY",
    "MARSH",
    "MASSE",
    "MATEY",
    "MAXIM",
    "MEDAL",
    "MERIT",
    "METAL",
    "MIDGE",
    "MIDST",
    "MIMIC",
    "MINCE",
    "MODEL",
    "MOIST",
    "MOLAR",
    "MONEY",
    "MONTH",
    "MOTOR",
    "MOTTO",
    "MOULT",
    "MOUNT",
    "MOURN",
    "MOVIE",
    "MUCKY",
    "MUMMY",
    "NAIVE",
    "NASTY",
    "NATAL",
    "NAVAL",
    "NEEDY",
    "NIGHT",
    "NINTH",
    "NYMPH",
    "OFFAL",
    "OLIVE",
    "ONSET",
    "OPERA",
    "OTHER",
    "OUGHT",
    "OUTDO",
    "OXIDE",
    "PANEL",
    "PANIC",
    "PAPER",
    "PARER",
    "PARRY",
    "PATTY",
    "PAUSE",
    "PEACH",
    "PERCH",
    "PERKY",
    "PHASE",
    "PHOTO",
    "PICKY",
    "PIETY",
    "PILOT",
    "PIXIE",
    "PINEY",
    "PINTO",
    "PITHY",
    "PLANT",
    "PLEAT",
    "PLUCK",
    "POINT",
    "POISE",
    "POKER",
    "POUND",
    "POWER",
    "PRICK",
    "PRIDE",
    "PRIME",
    "PRIMO",
    "PRINT",
    "PRIZE",
    "PROBE",
    "PROVE",
    "PROXY",
    "PULPY",
    "PURGE",
    "QUART",
    "QUERY",
    "QUIET",
    "QUIRK",
    "RADIO",
    "RAINY",
    "REACT",
    "REBUS",
    "REBUT",
    "RECAP",
    "RENEW",
    "REPAY",
    "RETCH",
    "RETRO",
    "RHINO",
    "RHYME",
    "RIVAL",
    "ROBIN",
    "ROBOT",
    "ROGUE",
    "ROOMY",
    "ROUGE",
    "ROUND",
    "ROYAL",
    "RUDER",
    "RUPEE",
    "RUSTY",
    "SAINT",
    "SALAD",
    "SALSA",
    "SAUTE",
    "SCALD",
    "SCARE",
    "SCOLD",
    "SCORN",
    "SCOUR",
    "SCRAP",
    "SEDAN",
    "SEEDY",
    "SERVE",
    "SEVER",
    "SHAKE",
    "SHALL",
    "SHAME",
    "SHARD",
    "SHAWL",
    "SHINE",
    "SHIRE",
    "SHIRK",
    "SHOWN",
    "SHOWY",
    "SHRUB",
    "SHRUG",
    "SIEGE",
    "SISSY",
    "SKILL",
    "SKIRT",
    "SLATE",
    "SLEEK",
    "SLOSH",
    "SLOTH",
    "SLUMP",
    "SLUNG",
    "SMART",
    "SMEAR",
    "SMELT",
    "SMITE",
    "SNARL",
    "SNEAK",
    "SNOUT",
    "SOGGY",
    "SOLAR",
    "SOLVE",
    "SONIC",
    "SOUND",
    "SOWER",
    "SPADE",
    "SPELL",
    "SPEND",
    "SPICY",
    "SPIEL",
    "SPIKE",
    "SPILL",
    "SPIRE",
    "SPOKE",
    "SPRAY",
    "SQUAD",
    "STAFF",
    "STAGE",
    "STAIR",
    "STALE",
    "STAND",
    "START",
    "STEAD",
    "STEED",
    "STEIN",
    "STICK",
    "STING",
    "STINK",
    "STOMP",
    "STOOL",
    "STORE",
    "STORY",
    "STOUT",
    "STOVE",
    "STUDY",
    "SUGAR",
    "SURER",
    "SWEET",
    "SWILL",
    "SWIRL",
    "TACIT",
    "TANGY",
    "TAPER",
    "TAPIR",
    "TASTY",
    "TAUNT",
    "TEASE",
    "TEPID",
    "THEIR",
    "THEME",
    "THERE",
    "THIRD",
    "THORN",
    "THOSE",
    "THUMB",
    "THYME",
    "TIARA",
    "TIBIA",
    "TIGER",
    "TILDE",
    "TIPSY",
    "TODAY",
    "TORSO",
    "TOTEM",
    "TRACE",
    "TRAIN",
    "TRAIT",
    "TRASH",
    "TRAWL",
    "TREAT",
    "TRIAD",
    "TRICE",
    "TRITE",
    "TROLL",
    "TROPE",
    "TROVE",
    "TRUSS",
    "TRYST",
    "TWANG",
    "TWEED",
    "TWICE",
    "TWINE",
    "ULCER",
    "ULTRA",
    "UNDUE",
    "UNFED",
    "UNFIT",
    "UNIFY",
    "UNITE",
    "UNLIT",
    "UNMET",
    "UPSET",
    "USAGE",
    "USHER",
    "USING",
    "USUAL",
    "USURP",
    "VALET",
    "VALID",
    "VIGOR",
    "VIRAL",
    "VITAL",
    "VIVID",
    "VODKA",
    "VOICE",
    "VOUCH",
    "WACKY",
    "WALTZ",
    "WASTE",
    "WATCH",
    "WEARY",
    "WEDGE",
    "WHACK",
    "WHELP",
    "WHINE",
    "WHOOP",
    "WINCE",
    "WOKEN",
    "WOOER",
    "WORLD",
    "WORRY",
    "WOVEN",
    "WROTE",
    "WRUNG",
    "YEARN",
    "YIELD",
    "YOUTH",
    "ZESTY",
  ];


var letter1 = {
    letter: 'g',
    position: 0,
    color: 'g',
};

var letter2 = {
    letter: 'x',
    position: 1,
    color: 'b'
};

var letter3 = {
    letter: 'i',
    position: 2,
    color: 'y'
};

var letter4 = {
    letter: 'y',
    position: 3,
    color: 'b'
};

var letter5 = {
    letter: 'z',
    position: 4,
    color: 'b'
};

var input = [letter1, letter2, letter3, letter4, letter5];




  /** arguments: array of five objects
   *    function needs to go through each obj:
   * => if (letterX.color === 'g'):
   *        - go through Array answers, push strings that do meet the condition into new array
   *        - after that, we only need to work with the new Array filteredAnswers
   *            - we will have an array of words with green letters
   * 
   * => if (letterX.color === 'b'):
   *        - go through Array filteredAnswers, remove strings that include the letter in any index
   *        - we will have an updated Array filteredAnswers
   * 
   * => if (letterX.color === 'y'):
   *        - remove any strings that have that letter in that index, update Array filteredAnswers
   *        - remove any strings that do not have that letter in the remaining indexes
   * 
   *         
   *  
   *  return: an array of words that have 
   *    - the perfect letters in the right positions
   *    - eliminate any words with yellow letter in yellow position, but include that letter in the word
   *    - eliminate any words that have a black letter
   * 
   * 
   */

function wordle(inputArray) {
    var filteredAnswers = answers;
    for (var i = 0; i < inputArray.length; i++) {
        var letter = inputArray[i].letter.toUpperCase();
        var position = inputArray[i].position;
        // check if any our letter is green
        if (inputArray[i].color === "g") {
            // go through Array answers, push strings that do meet the condition into new array
            filteredAnswers = filteredAnswers.filter(word => word.charAt(position) === letter);
        }
        // check if any our letter is black
        if (inputArray[i].color === "b") {
            //go through Array filteredAnswers, remove strings that include the letter in any index
            filteredAnswers = filteredAnswers.filter(word => word.includes(letter) !== true);
        }
        // check if any our letter is yellow 
        if (inputArray[i].color === "y") {
            // remove any strings that do not have that letter in the indexes
            filteredAnswers = filteredAnswers.filter(word => word.includes(letter));
            // remove any strings that have that letter in that index, update Array filteredAnswers
            filteredAnswers = filteredAnswers.filter(word => word.charAt(position) !== letter);
            

        }
    }
    console.log(filteredAnswers);
    
   
    

    
    

    


}

wordle(input);




  
  
  
  
  
  
  
  
  
  
  
  
  